ALTER TABLE settings
  ADD COLUMN annual_leave_accrual_policy TEXT NOT NULL DEFAULT 'YEAR_START',
  ADD COLUMN carry_over_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN carry_over_limit_hours DOUBLE PRECISION NOT NULL DEFAULT 0;
